Sparkui reverse proxyfix
saagie/technologies pull request #210
Opened 2020-12-01 09:39 UTC by PierreLeresteux

Modify JS to match reverse proxy

2020-12-01 16:52 UTC, finalspy requested changes
Quelques remarques plus sur la forme et nmotamment les retour a la ligne en fin de fichiers, et sur les commentaires expliquant le mecanisme mis en place pour forcer le rebuild.

Et sinon RUN de backup superflu ou a expliciteret si possible a reduire avec le suivant

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-2.4/Dockerfile
> +
Pourquoi faire 2 RUN et pas tout regrouper ? On reutilise vraiment la layer ?

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-2.4/Dockerfile
> +
D'ailleurs le backup ici a t'il vraiement un sens ? a supprimer non ?

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-2.4/innerContexts/python/Dockerfile
> +ENV REBUILD ME
Manque ligne vide en fin de fichier

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/Dockerfile
> +
Meme remarque le backup est il necessaire a conserver ici ? Et si oui pourquoi 2 RUN separes ?

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/assets/stagepage.js
> +/*
Dommage que l'on ne sache pas ce qui a ete customisé sur un si gros fichier ... un petit commentaire peut-etre ?

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/assets/utils.js
> +/*
meme remarque

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/assets/utils.js
> +}
manque le retour a la ligne en fin de fichier

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/assets/stagepage.js
> +});
manque le retour a la ligne en fin de fichier

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/innerContexts/jre/Dockerfile
> +
idem

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/innerContexts/jre/spark-3.0-jre-8/build.me
> +please
pourquoi pas keep ici ? un petit topo sur le pourquoi du comment du rebuild serait interessant non ?

2020-12-01 16:52 UTC, finalspy commented on technologies/job/spark/spark-3.0/innerContexts/python/Dockerfile
> +ENV REBUILD ME
manque le retour a la ligne

2020-12-11 15:25 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/assets/stagepage.js
> +/*
J'ai repris les fichiers de la PR ouverte chez Spark

2020-12-11 15:34 UTC, PierreLeresteux commented on technologies/job/spark/spark-2.4/Dockerfile
> +
removed

2020-12-11 15:34 UTC, PierreLeresteux commented on technologies/job/spark/spark-2.4/innerContexts/python/Dockerfile
> +ENV REBUILD ME
removed

2020-12-11 15:34 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/Dockerfile
> +
removed

2020-12-11 15:34 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/assets/utils.js
> +/*
J'ai repris les fichiers de la PR ouverte chez Spark

2020-12-11 15:35 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/assets/utils.js
> +}
Done

2020-12-11 15:35 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/assets/stagepage.js
> +});
Done

2020-12-11 15:35 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/innerContexts/jre/Dockerfile
> +
Removed

2020-12-11 15:35 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/innerContexts/jre/spark-3.0-jre-8/build.me
> +please
Done

2020-12-11 15:35 UTC, PierreLeresteux commented on technologies/job/spark/spark-3.0/innerContexts/python/Dockerfile
> +ENV REBUILD ME
Done

2020-12-17 10:17 UTC, finalspy approved these changes

2020-12-17 10:25 UTC, merged