Add ability to change default CRAN to custom value
saagie/technologies pull request #323
Opened 2021-08-31 11:30 UTC by finalspy

Sometimes it happens that you want your jobs to automatically be based on custom CRAN sites, wether you host your own private packages, or run saagie inside a secure environment with no access to external URLs.

This merge request allow to use a Saagie environment variable R_CUSTOM_CRAN to pass a specific URL to use by default.

Despite this change can be made manually inside an RScript, it remains usefull if the end users are agnostic about CRAN mechanisms.

2021-09-07 16:54 UTC, holyhope requested changes
Hello @finalspy,

Thank you for your contribution.

Can you please update the `technologies/job/r/r-*/buildMe` file (write what ever you want in it). The changes on these files wile trigger build for all `R` technologies (not only the `-base` one).

2021-09-07 17:34 UTC, holyhope requested changes

2021-09-07 17:34 UTC, holyhope commented on technologies/job/r/r-3.4.4-base/entrypoint
> +fi
I suggest to rename the variable `R_CRAN_URL`.
In a near future this variable will be `https://cloud.r-project.org` by default :-)
```suggestion
if [[ -z "${R_CRAN_URL}" ]]; then
    echo "No custom CRAN defined, using default, you can configure one using R_CRAN_URL env var"
else
    sed -i 's#https://cloud.r-project.org#'"${R_CRAN_URL}"'#g' /usr/lib/R/etc/Rprofile.site
fi
```

2022-02-03 15:23 UTC, TFellet commented
Modification taken into account starting from R 4.1. All older versions are now deprecated and will not be updated.

2022-02-03 15:23 UTC, closed without merging